### PR TITLE
Add connection squares

### LINKED ISSUE #2: Formalise Proposition 3.5 from RS17 paper
Should be straightforward, no HoTT preliminaries required.

### PR DESCRIPTION
**Pull request by jonalfcam**
Added proof of part of prop 3.5 (closes #2).

### CODE REVIEW

**Review by emilyriehl — COMMENTED** [review]
Let's swap the ->, |->, and <= to the unicode characters and then merge.

**Comment by emilyriehl** [comment]
Also we've been citing results from the paper as "RS17, Proposition 3.5" so as to distinguish from citations to Buchholtz-Weinberger or Bardomiano Martínez.

**Review by emilyriehl — COMMENTED** [review]
One more suggestion. The naming doesn't quite match the style guide:

https://github.com/rzk-lang/sHoTT/blob/main/src/STYLEGUIDE.md

The basic form of both term names should be something like "square-arrow" or "sq-arr" if you'd prefer to abbreviate. This should be thought of as something like function notation because the function "square-arrow" takes in an arrow "f" and returns a square "square-arrow f" (ignoring the type argument).

So perhaps "or-square-arrow" and "and-square-arrow"? Or "or-sq-arr" and "and-sq-arr"? I have no strong preference by maybe @fizruk does?

Otherwise I think this is ready to merge.

**Comment by fizruk** [comment]
> So perhaps "or-square-arrow" and "and-square-arrow"? Or "or-sq-arr" and "and-sq-arr"? I have no strong preference by maybe @fizruk does?

Maybe, `meet` and `join` should be used instead of `and` and `or` correspondingly?
Personally, I prefer full names, so how about `meet-square-arrow` and `join-square-arrow`?

**Comment by fizruk** [comment]
I've committed fixes to the mkdocs overrides in https://github.com/rzk-lang/sHoTT/pull/27/commits/56201f6e8412604a1e3bac6e0b2f14b9dcf9763f. Technically, it does not belong in this PR, but I used it to add the diagrams for the constructions (at the moment these are not generated automatically).

Screenshot 2023-09-20 at 10 03 07

**Review by fizruk — APPROVED** [review]
I think this can be merged now :)

**Pull request merged**
